version: "3"
services:
  my-jupyter:
    build: .
    container_name: tabnet_exp
    working_dir: /working
    ports:
      - 8888:8888
    volumes:
      - $PWD:/working
    environment:
      - PYTHONPATH=/working
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
